
maxpixel = 5;
offset_scale = 1;
offsets = BuildOffsetsAndColorMap(maxpixel,offset_scale);
solver = 'minsum';
numHsp = 10;
numWsp = 10;
do_similarity = 1;
k = 1e9;
ep     = 0.001;
sigmaP = 1;

GP5Benchmarks.addConstructor('BuildOpticalFlowGraph', @BuildOpticalFlowGraph);

results = compareSolvers(...
    'graphConstructor', 'BuildOpticalFlowGraph',...
    'itr', 3,...
    'solver', solver,...
    'offsets', offsets, ...
    'solver',solver, ...
	'numHsp', numHsp, ...
	'numWsp', numWsp, ...
	'doSimilarity', 1, ...
	'k', k, ...
	'ep', ep, ...
    'sigmaP', sigmaP,...
    'displayTimeLogs',true ...
);

pc = results.get('IntelMS');
gp5 = results.get('BehavioralMS');
pc/gp5
