

GP5Benchmarks.addConstructor('stereovision', @stereovision);

results = compareSolvers(...
    'graphConstructor', 'stereovision',...
    'itr', 3,...
    'solver', 'sumproduct',...
    'depth',75, ...
    'width', 13, ...
    'height', 13, ...
    'k', 0, ...
    'damping', 0, ...
    'scheduler', 'FloodingScheduler', ...
    'displayTimeLogs',true ...
);

pc = results.get('IntelMS');
gp5 = results.get('BehavioralMS');
pc/gp5
